spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://postgres:5432/notification_platform
  data:
    redis:
      host: redis
  kafka:
    bootstrap-servers: kafka:9092
